version: '3'
services:
    app:
      build: .
      ports:
      - 1234:80
      depends_on:
      - mysql
    mysql:
        image: mysql:5.6
        volumes: 
        -  ./src/main.sql:/docker-entrypoint-initdb.d/create_tables.sql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: main
            MYSQL_PASSWORD: YhXgSdHw9gT8tptMdRge
            MYSQL_DATABASE: main
